[phases.setup]
aptPkgs = ['curl', 'wget', 'git'] 
nixPkgs = ['bun']
[phases.install]
cmds = [
'curl -fsSL https://bun.sh/install | bash -s "bun-v1.2.2"',
'bun install --frozen-lockfile',
'bun run postinstall'
]
[phases.build]
cmds = [
'bun run clean',
'bun run build'
]
[start]
cmd = 'bun run start'
[variables]
NODE_ENV = 'production'
TURBO_TELEMETRY_DISABLED = '1'
BUN_VERSION = '1.2.2'  
[phases.setup.env]
NIXPACKS_BUN_PNPM_SUPPORT = 'true'
NIXPACKS_MONOREPO = 'true'

